import { defineConfig } from "vitest/config";
import { fileURLToPath } from "node:url";

/**
 * The site's testable logic is the build-time catalog resolution
 * (`src/lib/catalog.ts`) and the client-side access gate
 * (`src/components/ToolGate.tsx`). The `.astro` pages stay on `astro check` +
 * the real build.
 *
 * `virtual:tools-catalog` is generated by the `toolHost()` integration during
 * `astro build`, so it does not exist under vitest — it is aliased to a fixture
 * that mirrors a real composition (free / login-default / premium tools).
 */
export default defineConfig({
  test: {
    include: ["src/**/*.test.{ts,tsx}", "test/**/*.test.{ts,tsx}"],
    environment: "node",
    restoreMocks: true,
  },
  resolve: {
    alias: {
      "virtual:tools-catalog": fileURLToPath(
        new URL("./test/fixtures/tools-catalog.ts", import.meta.url),
      ),
      // Astro resolves `~/…` from tsconfig's paths; vitest does not read
      // those, so the alias has to be restated here or any module that
      // imports through it fails to load under test rather than failing an
      // assertion — which looks like a broken suite, not a broken import.
      "~": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
});
